version: "3"
services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pgvector

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - ./.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  uploadservice:
    build: ./uploadservice
    ports:
      - "4000:4000"
